# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'testTrigger/*'
      - 'testTrigger2/*'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world from successful trigger 'testTrigger/*'!
  displayName: 'Run a one-line script for testTrigger'
#  condition: and(succeeded(), eq(variables['testTriggerChanged'], 'true'))

- script: echo Hello, world from successful trigger 'testTrigger2/*'!
  displayName: 'Run a one-line script for testTrigger2'
#  condition: and(succeeded(), eq(variables['testTrigger2Changed'], 'true'))

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'