# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
#  paths:
#    include:
#      - 'testTrigger/*'


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world from successful trigger 'testTrigger/*'!
  displayName: 'Run a one-line script'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/testTrigger/*'))

- script: echo Hello, world from successful trigger 'testTrigger2/*'!
  displayName: 'Run a one-line script'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/testTrigger2/*'))

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'